### ISSUE TITLE
On Rpi 3B+ sometimes upon re/boot sound card,device doesn't equal 1,0

### ISSUE THREAD

**Issue by scottveirs** [orcasound/orcanode#14]
If .env file has specified hardware device as 1,0 this behavior means there are no data generated even though ffmpeg and s3fs appear to be running (via htop).

**Comment by scottveirs** [comment]
Revealed today at Port Townsend node via: 
```
aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
```

**Comment by scottveirs** [comment]
Bush Point working shows this via `aplay -l` -- 

```
card 1: pisound [pisound], device 0: PS-3VGC9QJ snd-soc-dummy-dai-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by scottveirs** [comment]
Whereas Port Townsend shows (even after a Dataplicity reboot): 
```
card 0: pisound [pisound], device 0: PS-3KF2GYN snd-soc-dummy-dai-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by mcshicks** [comment]
Will look into fixing this by adding support for device names, i.e. pisound instead of numbers

**Comment by mcshicks** [comment]
At least for rapsberry pi with  pisound card and jack you can just use AUDIO_HW_ID=pisound

**Comment by scottveirs** [comment]
Just noting for the historical record this happened yesterday at the Bush Point node (for the first time I think) upon a power outage on Whidbey Island. `arecord -l` showed 0,0 but .env file variable expected 1,0 ...  Re-booting Rpi via Dataplicity solved the issue; when it came back online `arecord -l` showed the expected 1,0.
