### ISSUE TITLE
LogDNA broken

### ISSUE THREAD

**Issue by orcasoundapp** [orcasound/orcanode#17]
Not sure why but the logging containers became disconnected from app.logdna.com Orcasound account sometime in late 2019...

**Comment by mcshicks** [comment]
Will investigate when adding support for mulitple archtectures from single branch

**Comment by mcshicks** [comment]
I don't see this happening on the mseed branch, I tested both mseed on amd64 branch and rpi branc and it seemed like the logging messages worked fine.  I will close for now and if someone can reproduce the issue we can reopen
