### ISSUE TITLE
Add support to stream.sh to enable/disable flac archive based on environment variable 

### ISSUE THREAD

**Issue by mcshicks** [orcasound/orcanode#2]
We want all nodes to stream hls and dash, but for high performance networks we would like to also create and archive flac.   We need different ffmpeg and S3 setup options for each

**Comment by scottveirs** [comment]
Implemented using .env variable NODE_TYPE which currently can be set to "research" (FLAC+HLS), "debug" (DASH only), "hls-only", or default (FLAC+HLS+DASH). These three data streams have their own local directories, rsync calls to transfer to /mnt directories (watched by s3fs), and S3 buckets (stream vs archive).
