### ISSUE TITLE
Make sampling rate for audio configurable by environment variable for stream.sh

### ISSUE THREAD

**Issue by mcshicks** [orcasound/orcanode#4]
The pisound board needs the sampling rate (-ar in ffmpeg) set to 192000.  This will break x86 so we need to make is configurable by environment variable

**Comment by scottveirs** [comment]
Now implemented via .env variables SAMPLE_RATE (and also STREAM_RATE). Should be able to utilize within resin.io as well, with these as device-specific environmental variables.
