### ISSUE TITLE
Replace figure with Orcasound Software Evolution Model

### ISSUE THREAD

**Issue by valentina-s** [orcasound/orcanode#60]
The figure goes right to left and warps my brain to read it 🤪. I created a version left to right [here](https://drive.google.com/file/d/115PtSojkF6qyEH9BdMhpTf9vH00TRqCB/view?usp=sharing) in `.png` and [here](https://drive.google.com/file/d/1YFTAQPqgtcTl6ubac0mgyQ7fvg0BZqzH/view?usp=sharing) in diagram format if one wants to use the opportunity to update it. I can submit PR to update it but the image is pulled from Orcasound website so best to update it there.
![OrcasoundSoftwareEvolutionModel](https://user-images.githubusercontent.com/11621647/218459404-18b8a1d6-b456-4d0e-8f40-4c265c299a9f.png)

**Comment by scottveirs** [comment]
At last, @valentina-s , I've used this nice improved graphic by replacing the original "right2left" version (on the orcasound.net server). I also linked to the working version (your Google Diagram) and a new archive of the schematics.

<img width="1052" alt="Screenshot 2023-06-13 at 3 35 58 PM" src="https://github.com/orcasound/orcanode/assets/14044595/623934c7-69da-4198-8a08-486b636e9102">

Thank you for making the new, more-intuitive left2right one!
