### ISSUE TITLE
How is it used?

### ISSUE THREAD

**Issue by Hello-2877515114** [orcasound/orcanode#69]
Hi friend, how will I copy it?
 I don't seem to find these links for detailed tutorials

**Comment by scottveirs** [comment]
Hi @Hello-2877515114 -- Please use [Discussions](https://github.com/orcasound/orcanode/discussions) to ask questions or give us specific feedback on our documentation after reading (at least) the [https://github.com/orcasound/orcanode](README at https://github.com/orcasound/orcanode) and the [orcanode wiki](https://github.com/orcasound/orcanode/wiki).
